version: '3'
services:
  jss_db:
    container_name: jss_db
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  jss_node:
    container_name: jss_node
    image: "jss_node:1.0.0"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    links:
      - jss_db:jss_db
    depends_on:
      - jss_db
    command: >
      sh -c "./src/bin/wait-for.sh jss_db:${DATABASE_PORT}
      && npm run dev"
